<?php

/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Magento\Framework\Escaper $escaper */
//Magento_Ui/js/form/components/insert-form
/** @var \Training\Feedback\ViewModel\FeedbackForm $viewModel */
$viewModel = $block->getData('view_model');
?>

<form class="form contact"
      action="<?= $escaper->escapeUrl($viewModel->getFeedbackFormActionUrl()) ?>"
      id="feedback-form"
      method="post"
      data-hasrequired="<?= $escaper->escapeHtmlAttr(__('* Required Fields')) ?>"
      data-mage-init='{"validation":{}}'
>
    <fieldset class="fieldset">
        <legend class="legend">
            <span><?= $escaper->escapeHtml(__('Leave your feedback')) ?></span>
        </legend><br/>
        <div class="field name">
            <label class="label" for="author_name">
                <span><?= $escaper->escapeHtml(__('Name')) ?></span>
            </label>
            <div class="control">
                <input name="author_name" id="author_name"
                       title="<?= $escaper->escapeHtmlAttr(__('Name')) ?>" value=""
                       class="input-text" type="text" data-validate="{required:true}"/>
            </div>
        </div>
        <div class="field email required">
            <label class="label" for="author_email">
                <span><?= $escaper->escapeHtml(__('Email')) ?></span>
            </label>
            <div class="control">
                <input name="author_email" id="author_email" title="<?= $escaper->escapeHtmlAttr(__('Email')) ?>" value=""
                class="input-text" type="email" data-validate="{required:true, 'validate-email':true}"/>
            </div>
        </div>
        <div class="field sku">
            <label class="label" for="related_products_sku">
                <span><?= $escaper->escapeHtml(__('Related products sku')) ?></span>
            </label>
            <div class="control">
                <input name="related_products_sku" id="related_products_sku"
                       title="<?= $escaper->escapeHtmlAttr(__('Related products sku')) ?>"
                       value=""
                       class="input-text" type="text" data-validate="{}"/>
            </div>
        </div>
        <div class="field comment required">
            <label class="label" for="message">
                <span><?= $escaper->escapeHtml(__('What’s on your mind?')) ?></span>
            </label>
            <div class="control">
                <textarea name="message" id="message"
                title="<?= $escaper->escapeHtmlAttr(__('What’s on your mind?')) ?>"
                class="input-text" cols="5" rows="3" data-validate="{required:true}"></textarea>
            </div>
        </div>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <input type="hidden" name="hideit" id="hideit" value=""/>
            <button type="submit" title="<?= $escaper->escapeHtmlAttr(__('Submit')) ?>" class="action submit primary">
                <span><?= $escaper->escapeHtml(__('Submit')) ?></span>
            </button>
        </div>
    </div>
</form>

<!--<div data-bind="scope: 'feedbackForm'">-->
<!-- ko template: getTemplate() --><!-- /ko -->
<!--</div>-->
<!---->
<!--<script type="text/x-magento-init">-->
<!--{-->
<!--   "*": {-->
<!--       "Magento_Ui/js/core/app": {-->
<!--           "components": {-->
<!--               "feedbackForm": {-->
<!--                   "component":"Training_Feedback/js/component/feedback_form",-->
<!--                   "config": {-->
<!--                       "template":"Training_Feedback/feedback_form",-->
<!--                       "url":"--><?php //echo $escaper->escapeJs( $viewModel->getFeedbackFormActionUrl()) ?><!--"-->
<!--                    }-->
<!--                }-->
<!--            }-->
<!--        }-->
<!--    }-->
<!--}-->
<!--</script>-->
