<?php
/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Magento\Framework\Escaper $escaper */
/** @var \Training\Feedback\ViewModel\FeedbackForm $feedbackFormVM */
/** @var \Training\FeedbackProduct\ViewModel\RelatedProducts $feedbackRelatedProductsVM */

$feedbackFormVM = $block->getData('form_view_model');
$feedbackRelatedProductsVM = $block->getData('related_products_view_model');
?>

<div>
    <div class="toolbar">
        <div class="action">
            <button id="add" title="<?php __('Add Feedback') ?>"
                    type="button" class="action scalable primary"
                    onclick="location.href = '<?php echo $block->escapeUrl($feedbackFormVM->getFeedbackFormUrl()) ?>';"
            >
                <span><?php echo __('Add feedback') ?></span>
            </button>
        </div>
        <?= $block->getPaginationHtml() ?>
    </div>
    <div class="feedback-list">
        <?php
        /** @var \Training\Feedback\Api\Data\FeedbackInterface $feedback */
        foreach ($block->getFeedbackCollection() as $feedback):
        ?>
        <div class="feedback-item" style="background-color: #55ecf4; margin: 5px;">
            <p>
                <?= $escaper->escapeHtml($feedback->getAuthorName()) ?>
                <?= $block->getFeedbackDate($feedback); ?>
            </p>
            <p>
                <?= $escaper->escapeHtml($feedback->getMessage()) ?>
            </p>
            <p>
                <span>Related products: </span>
                <?php
                    $relatedProducts = $feedbackRelatedProductsVM->getRelatedProducts($feedback);
                    /** @var \Magento\Catalog\Api\Data\ProductInterface $relatedProduct */
                    foreach ($relatedProducts as $relatedProduct) {
                        echo $relatedProduct->getSku();
                    }
                ?>
            </p>
        </div>
        <?php endforeach; ?>
    </div>
    <div class="toolbar">
        <?= $block->getPaginationHtml() ?>
    </div>
</div>
